version: '3.8'

services:
  app:
    build: .
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: ["sh", "-c", "flask db upgrade && flask run --host=0.0.0.0"]
